apiVersion: apps/v1
kind: Deployment
metadata:
  name: vae-hmm-serving
  labels:
    app: vae-hmm-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vae-hmm-serving
  template:
    metadata:
      labels:
        app: vae-hmm-serving
    spec:
      containers:
        - name: vae-hmm-serving
          image: REPO/vae-hmm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MODE
              value: "serve-prod"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
